theme: minima
title: ns408.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Page to share
  stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
show_downloads: false
google_analytics: UA-115540513-1
github: [metadata]
